spring:
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/master_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: master_root_password
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/master_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: slave_root_password
